### ISSUE TITLE
Skills after "Occupational" won't roll

### ISSUE THREAD

**Issue by GhostShotIV** [GhostShotIV/IK-Foundry-Templates#1]
Skills after "Occupational" won't roll

**Comment by GhostShotIV** [comment]
Formula.js:509 Uncaught (in promise) Error: Uncomputable token sameRow(SkillTotalOcp)
    at sameRow (Formula.js:509:35)
    at math.js:26516:56
    at Object.evaluate (math.js:24162:45)
    at r.evaluate (math.js:24139:55)
    at Formula.computeStatic (Formula.js:858:27)
    at Formula.compute (Formula.js:442:21)
    at processFormulas (ComputablePhrase.js:139:35)
    at async processFormulas (ComputablePhrase.js:131:44)
    at async ComputablePhrase.compute (ComputablePhrase.js:212:34)
    at async HTMLAnchorElement.<anonymous> (Label.js:271:21)

**Comment by GhostShotIV** [comment]
Fixed with 0.1.8
